version: '3.3'
networks:
  proxy:       
    external: false  # ðŸ‘ˆ This line is not needed, as it is set to false by default
    name: proxy

services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./vhost.d:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro  

  #   networks:
  #     - proxy


  # letsencrypt:
  #   image: nginxproxy/acme-companion
  #   container_name: nginx-proxy-acme
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./vhost.d:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/var/run/docker.sock:ro


  #   depends_on:
  #     - nginx-proxy
  #   environment:
  #     - NGINX_PROXY_CONTAINER=nginx-proxy

  #   networks:
  #     - proxy


  frontend:
    build: .
    container_name: frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
             
    # environment:
    #   - VIRTUAL_HOST=walocho.co.ke    
    #   - VIRTUAL_PATH=/   
    #   - LETSENCRYPT_HOST=walocho.co.ke   
    #   - LETSENCRYPT_EMAIL=naxoduor7@gmail.com 

    networks:
      - proxy

